### ISSUE TITLE
Scripts not working on Windows

### ISSUE THREAD

**Issue by Driphter** [randombyte-developer/kt-skript#1]
I'm getting this error in the console:

```
error: illegal escape: '\N'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))
                                                                                    ^
error: illegal escape: '\.'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))
                                                                                               ^
error: illegal escape: '\c'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))
                                                                                                 ^
error: illegal escape: '\k'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))
                                                                                                        ^
error: illegal escape: '\s'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))
                                                                                                                  ^
error: illegal escape: '\o'
val script = KtSkriptScript("opCommandLogger", Paths.get("C:\New folder\.\config\kt-skript\scripts\opCommandLogger.ktskript"))

**Comment by randombyte-developer** [comment]
Uhh, right. Good catch. Will fix that soon. Thanks!

**Comment by randombyte-developer** [comment]
Try https://github.com/randombyte-developer/kt-skript/releases/tag/v1.1.1

**Comment by Driphter** [comment]
Hey, that fixed it! Thanks for the quick response.

Regarding Windows compatibility, though, I'm getting these errors in the console. My test script works fine, but I just thought you'd like to be made aware:

```
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.diagnostic.DefaultLogger:warn:57]: WARN: Failed to initialize native filesystem for Windows
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:82)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:161)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:321)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:62)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:54)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:61)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:43)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:60)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:83)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:129)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:44)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:197)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$4.create(ConcurrentFactoryMap.java:224)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:63)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:377)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:358)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:120)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$6.invoke(KotlinCoreEnvironment.kt:240)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$6.invoke(KotlinCoreEnvironment.kt:120)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:247)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:120)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:433)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:63)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:53)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:51)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:45)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:51)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:53)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.createState(KotlinJsr223JvmLocalScriptEngine.kt:57)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.createState$default(KotlinJsr223JvmScriptEngineBase.kt:46)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:72)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at de.randombyte.ktskript.script.ScriptsManager.loadScripts(ScriptsManager.kt:143)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at de.randombyte.ktskript.KtSkriptPlugin.reloadAllScripts(KtSkriptPlugin.kt:110)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at de.randombyte.ktskript.KtSkriptPlugin.reload(KtSkriptPlugin.kt:83)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at de.randombyte.ktskript.KtSkriptPlugin.onInit(KtSkriptPlugin.kt:65)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.common.event.listener.GameInitializationEventListener_KtSkriptPlugin_onInit1.handle(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:223)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:246)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[17:42:28] [Server thread/INFO] [STDERR]: [org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32:<clinit>:54]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by randombyte-developer** [comment]
Will look into it.

**Comment by randombyte-developer** [comment]
https://github.com/arturbosch/detekt/issues/630#issuecomment-353211225

**Comment by randombyte-developer** [comment]
Try setting the system property `idea.use.native.fs.for.win` to `false`, according to the issue it solves the warning. 

Edit: Probably with [Setx](https://ss64.com/nt/setx.html).

**Comment by randombyte-developer** [comment]
Any success?

**Comment by randombyte-developer** [comment]
It works, confirmed by @skmedix. The property will be set to false automatically when a Windows environment is detected in the upcoming version.
