### ISSUE TITLE
onPlayerLogin Event

### ISSUE THREAD

**Issue by OldKingisdie** [randombyte-developer/kt-skript#2]
I copy the script  from playeronjoin example
But the console report a error and the skript useless
```
javax.script.ScriptException: Error: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public val TargetEntityEvent.player: Player defined in de.randombyte.ktskript.utils.events
    "nucleus:warp ${player.name} main-spawn",
                    ^
error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public val TargetEntityEvent.player: Player defined in de.randombyte.ktskript.utils.events
    """title ${player.name} title {"text": "Welcome!", "color": "blue"}"""
               ^

        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:77) ~[KotlinJsr223JvmScriptEngineBase.class:?]
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compile(KotlinJsr223JvmScriptEngineBase.kt:35) ~[KotlinJsr223JvmScriptEngineBase.class:?]
        at de.randombyte.ktskript.script.ScriptsManager.loadScripts(ScriptsManager.kt:142) ~[ScriptsManager.class:?]
        at de.randombyte.ktskript.KtSkriptPlugin.reloadAllScripts(KtSkriptPlugin.kt:116) ~[KtSkriptPlugin.class:?]
        at de.randombyte.ktskript.KtSkriptPlugin.access$reloadAllScripts(KtSkriptPlugin.kt:33) ~[KtSkriptPlugin.class:?]
        at de.randombyte.ktskript.KtSkriptPlugin$setupFolderWatchers$1.invoke(KtSkriptPlugin.kt:93) ~[KtSkriptPlugin$setupFolderWatchers$1.class:?]
        at de.randombyte.ktskript.KtSkriptPlugin$setupFolderWatchers$1.invoke(KtSkriptPlugin.kt:33) ~[KtSkriptPlugin$setupFolderWatchers$1.class:?]
        at de.randombyte.ktskript.FolderWatcher.checkForChanges(FolderWatcher.kt:42) ~[FolderWatcher.class:?]
        at de.randombyte.ktskript.FolderWatcher.access$checkForChanges(FolderWatcher.kt:12) ~[FolderWatcher.class:?]
        at de.randombyte.ktskript.FolderWatcher$setupTask$1.run(FolderWatcher.kt:33) ~[FolderWatcher$setupTask$1.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3206]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_144]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2705-7.1.0-BETA-3206]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:325) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3206]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:662) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:597) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by randombyte-developer** [comment]
Try to change 'player' to 'causingPlayer'

**Comment by OldKingisdie** [comment]
OK，I will try this～～～
